In [1]:
# Using Numpy 
import numpy as np 

In [2]:
# Creating Arrays 
first_list = [1, 2, 3] 
np.array(first_list) 

array([1, 2, 3])

In [3]:
first_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(first_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Some Built in Methods 
np.arange(0, 10) # from 0 - 9 


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2) # start stop & step 

array([ 0,  2,  4,  6,  8, 10])

In [8]:
# Generating an array of zeros and ones 
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 2 x 2 arrays 
np.zeros((5, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3) 

array([1., 1., 1.])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# linspace => evenly spaced numbers 
np.linspace(0, 10, 3) 

array([ 0.,  5., 10.])

In [14]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
# Creating random numbers 
np.random.rand(5) # random number between 0 and 1 

array([0.37707472, 0.81086127, 0.09352221, 0.25602944, 0.3008385 ])

In [16]:
np.random.rand(5, 5)

array([[0.73561491, 0.41941326, 0.35524423, 0.74748209, 0.72300717],
       [0.45954363, 0.31688212, 0.40827722, 0.72307858, 0.19482918],
       [0.98819528, 0.5286694 , 0.70755533, 0.11496807, 0.01994378],
       [0.61123171, 0.78957462, 0.44687036, 0.9469732 , 0.28282393],
       [0.93794312, 0.39391771, 0.72221132, 0.09421059, 0.1846517 ]])

In [17]:
# negative numbers 
np.random.randn(5, 5) 

array([[-0.00897834,  0.03834174,  0.35897326, -0.35144463, -1.68400918],
       [-1.16688773,  1.12691568, -0.64088381, -1.40826688, -0.91882806],
       [-0.3299242 ,  0.95428296, -1.61055009,  0.71941583,  1.48145875],
       [ 0.52371392, -0.34352753, -0.52627491, -1.74320767, -1.6712196 ],
       [ 0.6386317 , -0.92432544, -1.50982486, -1.87194904, -0.51734672]])

In [18]:
# RandInt => random integers from low to high 
np.random.randint(1, 100)

96

In [19]:
np.random.randint(1, 100, 5)

array([20, 60, 11, 65, 10])

In [21]:
# Array Attributes and Methods 
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([16, 14,  7,  2, 44, 20, 19,  3,  6,  9])

In [24]:
# Reshape array 
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
# getting maximum, minimum, argmax & argmin 
ranarr

array([16, 14,  7,  2, 44, 20, 19,  3,  6,  9])

In [34]:
ranarr.min() 

2

In [35]:
ranarr.max() 

44

In [36]:
ranarr.argmax() # location of highest number, index 4. 

4

In [38]:
ranarr.argmin() # location of the lowest number, index 3

3

In [39]:
# Shape 
arr.shape 

(25,)

In [42]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [43]:
arr.reshape(1, 25).shape

(1, 25)

In [44]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [45]:
arr.reshape(25, 1).shape

(25, 1)

In [47]:
# Numpy Indexing and Selection 
fav_numbers = np.arange(0, 11)
fav_numbers 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# select value at index 5 
fav_numbers[5]

5

In [49]:
# select values between index 2 and 5 
fav_numbers[2:5]

array([2, 3, 4])

In [51]:
# Changing values 
fav_numbers[0:5] = 100 
fav_numbers

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
slicing = arr[0:10]
slicing

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# Matrices =>  2D Array
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [30, 35, 40]))
arr_2d 

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [58]:
arr_2d[1]

array([20, 25, 30])

In [59]:
arr_2d[1][2]

30

In [60]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [62]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [65]:
arr_2d[2, :]

array([30, 35, 40])

In [66]:
# Operations 
ops = np.arange(0, 10)

In [67]:
ops 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
ops + ops 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
ops - ops 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
ops * ops 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [72]:
ops ** 10 

array([         0,          1,       1024,      59049,    1048576,
          9765625,   60466176,  282475249, 1073741824, 3486784401])

In [73]:
# Taking Square Roots 
np.sqrt(ops)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [74]:
np.max(ops)

9